### ISSUE TITLE
Having trouble changing state of checkbox

### ISSUE THREAD

**Issue by slowlysteadily** [LluisRamon/relenium#10]
Thanks for your work on the the R port of Selenium - I have been wanting something like this for some time. However, I have run into a problem in that I cannot change the state of a checkbox on a certain web page. I thought the click method would work but apparently it does not. Do I misunderstand the approach or is this feature perhaps broken as regards check boxes?

```
library(relenium)
firefox <- firefoxClass$new()
firefox$get("http://jamaserv.jama.or.jp/newdb/eng/prod4/prod4TsMkEntry.html")
firefox$printHtml()

chkbox <- firefox$findElementByXPath("//input[@name='chkCarMaker4All'][@type='checkbox']")

chkbox$isSelected()
chkbox$click()
chkbox$isSelected()
```

In the above using chkbox$isSelected() both before and after the click() returns the same TRUE result. Nothing appears to have changed? Should I be using a different method?

**Comment by LluisRamon** [comment]
Hi slowlysteadily,

It works for me: http://rpubs.com/Lluis_Ramon/relenium_issue_10

I'm working on a mac and using relenium 0.3.0 and seleniumJars 0.3. Which platform and relenium and seleniumJars versions are you using?

```
R.version
               _                           
platform       x86_64-apple-darwin10.8.0   
arch           x86_64                      
os             darwin10.8.0                
system         x86_64, darwin10.8.0        
status                                     
major          3                           
minor          0.2                         
year           2013                        
month          09                          
day            25                          
svn rev        63987                       
language       R                           
version.string R version 3.0.2 (2013-09-25)
nickname       Frisbee Sailing  
```

**Comment by slowlysteadily** [comment]
Lluis, thanks for taking a look at this. At least I know the syntax is correct but it's odd that this works fine on your machine and not mine. My version of R appears to be identical to yours (see below), but on Windows 7. I'm using relenium_0.3.0 and seleniumJars_0.3.0. I have another Windows box and a Linux notebook I can use to test this. Will try it out and get back to you. If you have any other suggestions I'd be happy to give them a go.

> R.Version()
> $platform
> [1] "i386-w64-mingw32"

$arch
[1] "i386"

$os
[1] "mingw32"

$system
[1] "i386, mingw32"

$status
[1] ""

$major
[1] "3"

$minor
[1] "0.2"

$year
[1] "2013"

$month
[1] "09"

$day
[1] "25"

$`svn rev`
[1] "63987"

$language
[1] "R"

$version.string
[1] "R version 3.0.2 (2013-09-25)"

$nickname
[1] "Frisbee Sailing"

**Comment by LluisRamon** [comment]
Hi slowlysteadily, 

It could be that your Firefox browser is not updated and some selenium methods doesn't work properly in your version. Your example worked on my Mac with Firefox version 12.  I updated to 26 and it still works. 

I have implemented two new methods for firefoxClass that will help you know which Firefox version you have:

```
library(relenium)
firefox <- firefoxClass$new()
firefox$getCapabilities()
firefox$getVersion()
```

In case your Firefox browser is not updated, you can try to get a recent version. I hope it works.

Lluís

**Comment by LluisRamon** [comment]
In case you have an updated Forefox browser (25+):

Surfing on the internet I found that you are experiencing a Selenium issue:

http://stackoverflow.com/questions/20837480/click-then-ctrl-click-not-working-with-selenium-java-2-39-firefox-26
https://code.google.com/p/selenium/issues/detail?id=6774

The above links gives you a solution changing the display settings for your computer to 100%.

**Comment by slowlysteadily** [comment]
Hi Luis, I don't think it's the browser as I am on the beta release channel so I think I'm reasonably up to date. In any case, the two pages to which you linked were very helpful. I did have my display settings set to 125% and returning this to 100% seems to have fixed the problem - I would never have thought of something like this. Checkboxes can now be selected and deselected via Relenium. Thank you for your detective work.

**Comment by LluisRamon** [comment]
Great!
