### ISSUE TITLE
install_github problems on windows

### ISSUE THREAD

**Issue by LluisRamon** [LluisRamon/relenium#2]
It could be proxy, SO question [How to install_github when there is a proxy](http://stackoverflow.com/questions/17783686/solution-how-to-install-github-when-there-is-a-proxy)

There is a devtools issue with external libraries: [install_github and dependencies not on CRAN](https://github.com/hadley/devtools/issues/190)

**Comment by hansthompson** [comment]
I am really interested in your project but I am having some trouble installing on my computer.  

Windows 8.1 
Rstudio 0.97.551
R 3.0.2
Java Version 7 Update 45

Error message from Rstudio:

Installing github repo seleniumJars/master from LluisRamon
Downloading seleniumJars.zip from https://github.com/LluisRamon/seleniumJars/archive/master.zip
Installing package from C:\Users\HANST~1\AppData\Local\Temp\RtmpgNQSTU/seleniumJars.zip
Installing seleniumJars
"C:/PROGRA~1/R/R-30~1.2/bin/x64/R" --vanilla CMD INSTALL "C:\Users\Hans T\AppData\Local\Temp\RtmpgNQSTU\devtools12102ab6559\seleniumJars-master" --library="C:/Users/Hans T/Documents/R/win-library/3.0"  \
  --install-tests 
- installing _source_ package 'seleniumJars' ...
  *\* R
  *\* inst
  *\* preparing package for lazy loading
  Error : .onLoad failed in loadNamespace() for 'rJava', details:
  call: fun(libname, pkgname)
  error: No CurrentVersion entry in Software/JavaSoft registry! Try re-installing Java and make sure R and Java have matching architectures.
  ERROR: lazy loading failed for package 'seleniumJars'
- removing 'C:/Users/Hans T/Documents/R/win-library/3.0/seleniumJars'

Error: Command failed (1)

**Comment by aleixrvr** [comment]
Have you tried reinstalling java (both 32 and 64 bits)? and after rJava?

**Comment by hansthompson** [comment]
I have reinstalled Java from https://www.java.com/en/.  On my home machine I tried installing on is 64 bit but I don't know if that is the version I that I downloaded.  I'll check when I go home.  

I did install.packages("rJava") afterwards and it looked like it installed fine. I'll also try maybe using the xlsx package because I know that also uses java and I've had trouble with that before.

**Comment by hansthompson** [comment]
Working fine now.  The default java download is for 32 bit.  I had to search for 64.  Thanks. Running smoothly.

**Comment by aleixrvr** [comment]
Great!

Enviado desde mi iPhone
