### ISSUE TITLE
$selectByValue error

### ISSUE THREAD

**Issue by timriffe** [LluisRamon/relenium#7]
I'm trying out relenium on this page: http://esa.un.org/wpp/unpp/panel_population.htm,
which contains a series of selection lists, and finally the option to download a .csv file of data.

Here's what I have so far:

``` r
library(relenium)
firefox <- firefoxClass$new()
firefox$get("http://esa.un.org/wpp/unpp/panel_population.htm")

# this is the xpath for the first item to selection, with options "Population" and "Population density"
selectElementVar <- firefox$findElementByXPath("//*[@id=\"AutoNumber1\"]/tbody/tr[5]/td[2]/table/tbody/tr/td[4]/form/font/p[1]/table/tbody/tr/td[1]/font/select")
# the path contained double quotes, so I slashed them like so \", and things seem to work.

# so far so good:
optsListVar <- selectElementVar$getOptions() 
(AllVars <- sapply(optsListVar, function(optEle){
            optEle$getText()
        }))
# [1] "Population"         "Population density"

# per the examples, I try:
selectElementVar$selectByValue("Popualtion")
# and get the error:
#[1] "Error: NoSuchElementException"
#[1] "Thrown by Firefox$findElement(By by) and webElement$findElement(By by)." 

# same thing if I try:
# selectElementVar$selectByIndex(1)
```

In my code, I've created a bunch of selectElement's with different names to account for each of the boxes, though I doubt that is what's causing the error. Is this a bug or have I missed something key?

-very promising product! Happy to keep testing!
Tim

**Comment by aleixrvr** [comment]
Hey Tim!

I'm very happy you are starting to use it!

Many things:
1) There is a mispelling

selectElementVar$selectByValue("Popualtion")

should be "Population" ;)

2) Look at the html code:
<select name="Variable" multiple="" size="15">
<option value="12;">Population
</option><option value="14;">Population density
  </option></select>

The real "value" is "12;", so selectElementVar$selectByValue('12;') works
fine.

3) If you want to use the text, then
selectElementVar$selectByVisibleText('Population density')

4) The selectByIndex has another meaning:
selectByIndex:
Select the option at the given index. This is done by examing the "index"
attribute of an element, and not merely by counting.

so the 'index' is an attribute of the tag.

Thanks again! and if you see more things/have questions/whatever, let us
know!

Aleix

On Mon, Nov 11, 2013 at 10:25 PM, Tim Riffe notifications@github.comwrote:

> I'm trying out relenium on this page:
> http://esa.un.org/wpp/unpp/panel_population.htm,
> which contains a series of selection lists, and finally the option to
> download a .csv file of data.
> 
> Here's what I have so far:
> 
> library(relenium)firefox <- firefoxClass$new()firefox$get("http://esa.un.org/wpp/unpp/panel_population.htm")
> 
> # this is the xpath for the first item to selection, with options "Population" and "Population density"selectElementVar <- firefox$findElementByXPath("//*[@id=\"AutoNumber1\"]/tbody/tr[5]/td[2]/table/tbody/tr/td[4]/form/font/p[1]/table/tbody/tr/td[1]/font/select")# the path contained double quotes, so I slashed them like so \", and things seem to work.
> 
> # so far so good:optsListVar <- selectElementVar$getOptions() (AllVars <- sapply(optsListVar, function(optEle){            optEle$getText()        }))# [1] "Population"         "Population density"
> 
> # per the examples, I try:selectElementVar$selectByValue("Popualtion")# and get the error:#[1] "Error: NoSuchElementException"#[1] "Thrown by Firefox$findElement(By by) and webElement$findElement(By by)."
> 
> # same thing if I try:# selectElementVar$selectByIndex(1)
> 
> In my code, I've created a bunch of selectElement's with different names
> to account for each of the boxes, though I doubt that is what's causing the
> error. Is this a bug or have I missed something key?
> 
> -very promising product! Happy to keep testing!
> Tim
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/LluisRamon/relenium/issues/7
> .

## 

Premature optimization is the root of all evil (Knuth, D.)

Aleix Ruiz de Villa Robert

**Comment by timriffe** [comment]
doh! I was a dufus. Thanks for the tips, I'll see if I can get a full example

**Comment by markjoy** [comment]
Hi

New to the package - which looks great BTW

am trying:
library(relenium)

firefox=firefoxClass$new()
firefox$get("http://www.racingpost.com/membership/all.sd#")
inputElementUserName <- firefox$findElementByXPath(".//*[@id='loginForm-Username']")

I get the error:

[1] "Error: NoSuchElementException"
[1] "Thrown by Firefox$findElement(By by) and webElement$findElement(By by)."

the xpath comes from Firebug so I think it's OK, maybe not. Can you help?

Mark
