### ISSUE TITLE
Problem identifying real-world select box XPath

### ISSUE THREAD

**Issue by pssguy** [LluisRamon/relenium#9]
Worked through toy example fine but have hit a problem on a page where I want to extract all the currency codes from a select box

firefox <- firefoxClass$new()
firefox$get("http://www.xe.com/#")

There is a table on the page which I can extract
infoTable <- firefox$findElementByXPath("//*[@id='xRatesBxTable']")
readHTMLTable(infoTable$getHtml(), header = TRUE)[[1]] # this prints out

but the select box below it is proving problematic. Everything I try gives
e.g.
inputElement <- firefox$findElementByXPath("//*[@id='toInput']")
optsList <- selectElement$getOptions()
# [1] "Error: WebDriverException"
# [1] ""
# [1] "No options returned"

Could you give a hand with identifying correct XPath

TIA

**Comment by aleixrvr** [comment]
the getOptions function olny works with 'select' type tags. the xpath you give is from a div tag. 

I guess you want to deal with the 'input' tag inside the div. You have th click the 'down blue arrow' in the webpage:
inputElement <- firefox$findElementByXPath('//*[@id="to_sc"]')
inputElement$click()

and then either use the buttons 'scroll_down' or write the currency you want (see sendKeys in the documentation)
